server:
  port: 1234
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    context-path: /webchat

spring:
  application:
    name: web-chat
  profiles:
    active: dev

